server:
  port: 8080
  tomcat:
    connection-timeout: 1200000
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://192.170.1.201:3306/jiie
    username: root
    password: JiieDBP#ssw0rd#Dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

picturepath:
  local-user: "Sololan"
  db-url: "/pic/"
  nginx-url: ""
  loading-url: "C:/Users/${picturepath.local-user}/Desktop/pic/"
  upload-url: ${picturepath.loading-url}
  watermark-url: "${picturepath.loading-url}img-logo.png"